version: "3"
services:
    yolo_db_1:
        image: mysql
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        
        
    yolo_web_1:
         build:
            context: ./
            dockerfile: yolo_jboss.df
         image: yolo_jboss
         environment:
              - MYSQL_URI=yolo_db_1:3306
         depends_on:
              - yolo_db_1

         ports:
              - 8080:8080
        
